# NumPy
NumPy -> Numerical Python.

- It provides an extensive collection of high performance mathematical functions and multidimensional array objects.
- Numpy is designed to efficiently handle large arrays and perform numerical computations efficiently.

### _Creating NumPy array_
| Name | Example |
| :----: | :-------: |
| 0D   | Scalar  |
| 1D   | Vector  |
| 2D   | Matrix  |
| 3D   | Tensor  |


In [17]:
#creating 0D array with value 25
import numpy as np
arr = np.array(25)
print(arr)

25


In [18]:
#creating 1D array.
import numpy as np
a = np.array([1,2,3])
print(a) #This is vector


a
type(a)

[1 2 3]


numpy.ndarray

In [19]:
import numpy as np
b = np.array([[1,2,4],[4,5,6]])
print(b) #This is a matrix

[[1 2 4]
 [4 5 6]]


### _dtype_

In [20]:
import numpy as np
#np.array([1,2,3],dtype=float)
#np.array([1,2,3],dtype=bool)
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

### _arange()_
The `arange()` is used to create arrays with regularly spaced values within a specified range. It returns an array containing evenly spaced values starting from a specified start value and incrementing by a specified size.

In [24]:
import numpy as np
np.arange(10)
#np.arange(1,11)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### _`reshape()`_
The reshape function is used to change the shape or dimension of an array without its data. It returns a new view of the original aray with a different shape.

In [46]:
import numpy as np

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### _`ones()`_ and _`zeros()`_
ones() and zeros() are used to create arrays filled with ones and zeros, respectively. These functions allow you to quickly generate arrays of desired shape and data type, filled with ones and zeros.

In [26]:
import numpy as np
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [27]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### _`random.rand()`_
it provides functions for creating random numbers, random arrays, and performing random sampling. It allows you to incorporate randomness and simulate random processes in your data analysis or modelling tasks.

In [28]:
import numpy as np
np.random.rand(3,2)

array([[0.21147901, 0.57537949],
       [0.97872171, 0.11770377],
       [0.84115264, 0.95294036]])

In [ ]:
import numpy as np
np.random.uniform(1,10,(3,2)) #This will create a 3x2 array filled with random numbers, 1(inclusive) and ...

### _`linspace()`_
It is used to create arrays with evenly spaced values between a specified start and endpoint, inclusive. It allows you to define the number of elements ot the spacing between the values in the resulting array.

In [54]:
import numpy as np
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [50]:
import numpy as np
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

### _`identity()`_
The identity function is used to create an identity matrix, which is a square matrix with ones on the main diagonal and zeros elsewhere.

In [47]:
import numpy as np
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
import numpy as np
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### `Attibutes`
Bu default, np.arrange() creates arrays with data types int64. If you want to explicitly apecify the  datatype, you can pass the data type argument.

In [59]:
import numpy as np
a1 = np.arange(10,dtype = np.int32)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
a1

Some stuff goes here.

### _Itemsize_

In [ ]:
import numpy as np
a1 = np.array([1,2,3,4])
a1.itemsize

8

### _dtype_

In [ ]:
import numpy as np
a1 = np.array(3)
print(a1.dtype)

int64


### _Indexing & Slicing_

In [64]:
import numpy as np
a1 = np.arange(1,5) #=> [1,2,3,4]
a1[3] #slicing

4

In [40]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[0,1,0]

2

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:3,1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[1][1][1]

13

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0][1,:]

array([3, 4, 5])

In [ ]:
a3[0][1][:]

array([3, 4, 5])

In [ ]:
a3[1][:][1]

array([12, 13, 14])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
# I highly believe that some content goes here. and there is alot that I have not yet written in these pdfs.

# Iteration

In [ ]:
import numpy as np

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a1 
for i in a1:
    print(i, end = ' ')

0 1 2 3 4 5 6 7 8 9 

In [ ]:
for i in a2:
    print(i, end = ' ')

[0 1 2 3] [4 5 6 7] [ 8  9 10 11] 

In [ ]:
for i in a3:
    print(i, end = ' ')

[[0 1]
 [2 3]] [[4 5]
 [6 7]] 

In [ ]:
for i in a3:
    for j in i:
        for k in j:
            print(k, end = ' ')

0 1 2 3 4 5 6 7 

In [ ]:
for i in np.nditer(a3):
    print(i, end = ' ')

0 1 2 3 4 5 6 7 

# Reshaping

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2.reshape(4,3) #reshape() function

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a2.T #transpose() function

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### `ravel()`
In numpy it is used to flatten multi-dimensional arrays into one dimensional arrays by concatenating the elements of the array into row major order(c-style)

In [ ]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

# Stacking

In [ ]:
import numpy as np

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12, 24).reshape(3,4)
np.hstack((a4, a5))  #this is horizontal stacking


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.vstack((a4, a5)) #this is vertical stacking.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
np.hsplit(a4,3)

ValueError: array split does not result in an equal division

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]